// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpIzf7HmjHGqNZvQ-oVO5yA8ZVAQ1fH0c',
    appId: '1:1067703668919:web:380c45602154ced3f37d32',
    messagingSenderId: '1067703668919',
    projectId: 'fittrack-e62ee',
    authDomain: 'fittrack-e62ee.firebaseapp.com',
    storageBucket: 'fittrack-e62ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi6GFDy2QDK26emASiNHblWTX87gcZzkk',
    appId: '1:1067703668919:android:f22ac04592165b2ff37d32',
    messagingSenderId: '1067703668919',
    projectId: 'fittrack-e62ee',
    storageBucket: 'fittrack-e62ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwtyEqxgTEbHD9KOR54CZnAgpli0ryNIw',
    appId: '1:1067703668919:ios:5bfebc7aa82e6272f37d32',
    messagingSenderId: '1067703668919',
    projectId: 'fittrack-e62ee',
    storageBucket: 'fittrack-e62ee.appspot.com',
    iosBundleId: 'com.example.fittrackai',
  );
}
